name: Publish npm package

on:
  workflow_call:
    inputs:
      packagePath:
        description: 'Path to the package to publish'
        required: false
        type: string
        default: './'
      releaseType:
        description: 'Type of release to publish'
        required: false
        type: string
        default: 'patch'

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ${{ inputs.packagePath }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      #  TODO: add build command
      # - name: Install Dependencies
      #   run: |
      #     npm run co:login
      #     npm install
      #     npm run build

      # - name: Lint
      #   run: npm run lint --if-present

      # - name: Run Unit Tests
      #   run: npm run test:unit --if-present

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          version-type: ${{ inputs.releaseType }}
          skip-tag: true
          commit-message: 'chore: bumps version to {{version}} [skip ci]'

      # - name: 'Publish to CodeArtifact'
      #   run: npm publish
