name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
    uses: ./.github/workflows/publish-npm-package.yml
    secrets: inherit
    with:
      packagePath: './another-package'
