name: Publish Another

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'Type of release to publish'
        required: true
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    permissions:
      contents: write
    uses: ./.github/workflows/publish-npm-package.yml
    secrets: inherit
    with:
      packagePath: './another-package'
      releaseType: ${{ github.event.inputs.release_type }}
