name: Publish npm package

on:
  workflow_call:
    inputs:
      packagePath:
        description: 'Path to the package to publish'
        required: false
        type: string
        default: './'
      releaseType:
        description: 'Type of release to publish'
        required: false
        type: string
        default: 'patch'

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ${{ inputs.packagePath }}
    steps:
      - name: Validate releaseType
        run: |
          case "${{ inputs.releaseType }}" in
            patch|minor|major) ;;
            *) echo "Error: Invalid releaseType. Allowed values are 'patch', 'minor', 'major'." && exit 1 ;;
          esac

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      #  TODO: add build command
      # - name: Install dependencies and build
      #   run: |
      #     npm run co:login
      #     npm install
      #     npm run build

      # - name: Lint
      #   run: npm run lint --if-present

      # - name: Run Unit Tests
      #   run: npm run test:unit --if-present

      - name: Configure Git
        run: |
          git config --global user.name 'MikeyPartonBot[bot]'
          git config --global user.email '166193391+MikeyPartonBot[bot]@users.noreply.github.com'

      - name: 'Automated Version Bump'
        run: |
          npm version ${{ inputs.releaseType }} --git-tag-version false
          NEW_VERSION=$(cat package.json | jq -r '.version')
          PACKAGE_NAME=$(cat package.json | jq -r '.name')
          git commit -am "chore: bumps $PACKAGE_NAME to version $NEW_VERSION"
          git remote add origin_https https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git
          git push origin_https HEAD:master

      # - name: 'Publish to CodeArtifact'
      #   run: npm publish
