name: Publish Alt

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'Type of release to publish'
        required: true
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ./.github/setup-bot
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: ./.github/configure-release
        id: configure-release
