name: Publish

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Type of release to publish
        required: true
        default: patch
        options: [patch, minor, major]

jobs:
  configure-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      release-type: ${{ steps.configure-release.outputs.release-type }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/configure-release
        id: configure-release

  publish:
    if: ${{ needs.configure-release.outputs.release-type != '' }}
    needs: configure-release
    permissions:
      contents: write
    uses: ./.github/workflows/publish-npm-package.yml
    secrets: inherit
    with:
      releaseType: ${{ needs.configure-release.outputs.release-type }}
